//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogIntoServer", ReplyAction="http://tempuri.org/IService/ClientLogIntoServerResponse")]
        void ClientLogIntoServer(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogIntoServer", ReplyAction="http://tempuri.org/IService/ClientLogIntoServerResponse")]
        System.Threading.Tasks.Task ClientLogIntoServerAsync(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerSendMessageToClient", ReplyAction="http://tempuri.org/IService/ServerSendMessageToClientResponse")]
        void ServerSendMessageToClient(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerSendMessageToClient", ReplyAction="http://tempuri.org/IService/ServerSendMessageToClientResponse")]
        System.Threading.Tasks.Task ServerSendMessageToClientAsync(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerGetMessageFromClient", ReplyAction="http://tempuri.org/IService/ServerGetMessageFromClientResponse")]
        void ServerGetMessageFromClient(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerGetMessageFromClient", ReplyAction="http://tempuri.org/IService/ServerGetMessageFromClientResponse")]
        System.Threading.Tasks.Task ServerGetMessageFromClientAsync(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogOutOfServer", ReplyAction="http://tempuri.org/IService/ClientLogOutOfServerResponse")]
        void ClientLogOutOfServer(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogOutOfServer", ReplyAction="http://tempuri.org/IService/ClientLogOutOfServerResponse")]
        System.Threading.Tasks.Task ClientLogOutOfServerAsync(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        WpfApp1.Proxy.CompositeType GetDataUsingDataContract(WpfApp1.Proxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WpfApp1.Proxy.CompositeType> GetDataUsingDataContractAsync(WpfApp1.Proxy.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WpfApp1.Proxy.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WpfApp1.Proxy.IService>, WpfApp1.Proxy.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClientLogIntoServer(bool ClientisLoggedin) {
            base.Channel.ClientLogIntoServer(ClientisLoggedin);
        }
        
        public System.Threading.Tasks.Task ClientLogIntoServerAsync(bool ClientisLoggedin) {
            return base.Channel.ClientLogIntoServerAsync(ClientisLoggedin);
        }
        
        public void ServerSendMessageToClient(string clientMessage) {
            base.Channel.ServerSendMessageToClient(clientMessage);
        }
        
        public System.Threading.Tasks.Task ServerSendMessageToClientAsync(string clientMessage) {
            return base.Channel.ServerSendMessageToClientAsync(clientMessage);
        }
        
        public void ServerGetMessageFromClient(string clientMessage) {
            base.Channel.ServerGetMessageFromClient(clientMessage);
        }
        
        public System.Threading.Tasks.Task ServerGetMessageFromClientAsync(string clientMessage) {
            return base.Channel.ServerGetMessageFromClientAsync(clientMessage);
        }
        
        public void ClientLogOutOfServer(bool ClientisLoggedin) {
            base.Channel.ClientLogOutOfServer(ClientisLoggedin);
        }
        
        public System.Threading.Tasks.Task ClientLogOutOfServerAsync(bool ClientisLoggedin) {
            return base.Channel.ClientLogOutOfServerAsync(ClientisLoggedin);
        }
        
        public WpfApp1.Proxy.CompositeType GetDataUsingDataContract(WpfApp1.Proxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.Proxy.CompositeType> GetDataUsingDataContractAsync(WpfApp1.Proxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
